[[c_dependent]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d63cab5d8eb0f04d601dc0f165bf301cd3cae025"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_dependent.download]]
    sha256 = "43a982765451e81feb0cd5f06cc113666cc1db253a418560cb1994e6d9a8ece0"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "9c094663a5e3dc50e2609f32a4bbf8b417b64c68"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "626886916c21ae177b506afa5f001e5bbaf511c732114e7b9168bb459b7f443a"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu.tar.gz"
