[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "37c464e388e276d7aece2db084dd2d5886d6447e"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "338412a212cffb5ec5c98531ae487e148aef988183f507badef762b2bfd2d140"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_dependent]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a035510016cf003dcfa8b279535ecda10e412112"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_dependent.download]]
    sha256 = "f3508a14ffe1f91d27fc8146dcc142419cc33511e99551294cb07620c1d502d8"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
