[[c_dependent]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a035510016cf003dcfa8b279535ecda10e412112"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_dependent.download]]
    sha256 = "f3508a14ffe1f91d27fc8146dcc142419cc33511e99551294cb07620c1d502d8"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_dependent]]
arch = "armv7l"
git-tree-sha1 = "3821bf0c3777c2e1e90e15954c7f2d2e4bd3a78a"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "87063ba5dbb933b4f7a68d462ef5a63ab7126a067baf62897ccc1b8a83a9fda6"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.arm-linux-gnueabihf.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "e4d18c49d1d41382657e560e47d0d480616222d9"
os = "freebsd"

    [[c_dependent.download]]
    sha256 = "ec4c7f1dc3a43b4d74ee0791cfb3080ea855b3226cedd38b7ea1c742784f060d"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "b052a6bca392afc9a5226e7740c69fb268512ae5"
os = "macos"

    [[c_dependent.download]]
    sha256 = "f6bf224082afed17ecc1c21486a5608f999e158ac5cfacbf38f3935df0534df2"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-apple-darwin14.tar.gz"
[[c_dependent]]
arch = "powerpc64le"
git-tree-sha1 = "9c319eec600e77cb50ba1670c7cb14edaf619823"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "747f71c4864f12054356fbafd80204d4fdf2594ed9cd4ce505a252483d498fd3"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[c_dependent]]
arch = "i686"
git-tree-sha1 = "ed30f40f685f965a96b46e08aab7456579c8342d"
libc = "musl"
os = "linux"

    [[c_dependent.download]]
    sha256 = "4ffd44620829bae638847de96ac870e6e9fefb490aab6dd0d7d4b9fe548e1607"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.i686-linux-musl.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "25b49647ee5a1f3023b2de89efe26349c9fb6886"
libc = "musl"
os = "linux"

    [[c_dependent.download]]
    sha256 = "55087adf50460f0f380593c6ce861cef381598539f2323f3d57ff94bcfaa7c0d"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-musl.tar.gz"
[[c_dependent]]
arch = "i686"
git-tree-sha1 = "5d86937e6d137d26c4e14378bb2f8e9b0f38a79a"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "964603254d7b2e840c9861f55bdfd1481d7dbda2e40c9b98011a206f0a068f07"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.i686-linux-gnu.tar.gz"
[[c_dependent]]
arch = "i686"
git-tree-sha1 = "37702276b9f0f3198be603745891201799007392"
os = "windows"

    [[c_dependent.download]]
    sha256 = "c1780d62bf3413e9203313edf5b81e92ff98d8230be1baf3acc20a4ffeaa970b"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.i686-w64-mingw32.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "3db65f290aff77c88f5fe3c7d809906bbf78ec13"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "462aee74536b961e9b80c893ff904f5ecfd917c7bcfab2e5753895a3ad4a459b"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "743ae552b0ab9abb3f278dba327b2a3f771a7161"
os = "windows"

    [[c_dependent.download]]
    sha256 = "86eb0313cb4e772ead88a43ef04793b7a51779111c9a0bcfba6ff121162da740"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-w64-mingw32.tar.gz"
[[c_dependent]]
arch = "aarch64"
git-tree-sha1 = "7e71c6dffff8af71f30f4813e04fcdce92629979"
libc = "musl"
os = "linux"

    [[c_dependent.download]]
    sha256 = "f3164ad36e0993912749aa65ba030050fc89af8ebfa3a6ab6c5a7fa2f51d5dc2"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.aarch64-linux-musl.tar.gz"
[[c_dependent]]
arch = "aarch64"
git-tree-sha1 = "3d2d27166f1907169ad2d7824afcbaf24e6613c0"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "043228fc8edf9588439edfbacc77a995d8bafbda599aeedf513c3167995300a1"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.aarch64-linux-gnu.tar.gz"
[[c_dependent]]
arch = "armv7l"
git-tree-sha1 = "dd4033dc6c9eed0ba61782684bddbf6d00f11423"
libc = "musl"
os = "linux"

    [[c_dependent.download]]
    sha256 = "c8d3d5b815ff593816134b0cb2cf3d8fa833a120dea60a042350ef8b3d311725"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.arm-linux-musleabihf.tar.gz"
