[[c_dependent]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ff77e811708425c3024f6b9bb8fa6fcca1e645e"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_dependent.download]]
    sha256 = "43f5ef92e864e34b13ba8ed3da027ae75f1f773a3d95514a6beaaae4fb417240"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "5226994b693db2680bbc179a81d87922a3e82082"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "d15e6bfb9403778594777a1d2086c757c10ee0f599b3a992b9cfd01c4b49a009"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu.tar.gz"
