[[c_dependent]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ff77e811708425c3024f6b9bb8fa6fcca1e645e"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_dependent.download]]
    sha256 = "43f5ef92e864e34b13ba8ed3da027ae75f1f773a3d95514a6beaaae4fb417240"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_dependent]]
arch = "x86_64"
git-tree-sha1 = "72e1ae3e4b5a3dc6904ce6e0a3845e30b24d9bf6"
libc = "glibc"
os = "linux"

    [[c_dependent.download]]
    sha256 = "9d8cf9be94658fe923885fece6bcde86b24161ff478ca547285348d773136cb0"
    url = "https://github.com/JuliaBinaryWrappers/c_dependent_jll.jl/releases/download/c_dependent+v1.2.3+0/c_dependent.v1.2.3.x86_64-linux-gnu.tar.gz"
